mumble_plugin_main.h: include <cstring> for memset()
The MinGW builds failed with:

In file included from gtasa.cpp:6:0:
../mumble_plugin_main.h: In instantiation of 'T peekProc(const procptr_t&) [with T = unsigned char; procptr_t = long long unsigned int]':
gtasa.cpp:25:59:   required from here
../mumble_plugin_main.h:47:9: error: 'memset' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   memset(&ret, 0, sizeof(ret));
         ^
In file included from /usr/lib/mxe/usr/x86_64-w64-mingw32.static/include/guiddef.h:154:0,
                 from /usr/lib/mxe/usr/x86_64-w64-mingw32.static/include/winnt.h:635,
                 from /usr/lib/mxe/usr/x86_64-w64-mingw32.static/include/minwindef.h:163,
                 from /usr/lib/mxe/usr/x86_64-w64-mingw32.static/include/windef.h:8,
                 from /usr/lib/mxe/usr/x86_64-w64-mingw32.static/include/windows.h:69,
                 from ./../mumble_plugin_win32.h:21,
                 from ../mumble_plugin_main.h:95,
                 from gtasa.cpp:6:
/usr/lib/mxe/usr/x86_64-w64-mingw32.static/include/string.h:53:18: note: 'void* memset(void*, int, size_t)' declared here, later in the translation unit
   void * __cdecl memset(void *_Dst,int _Val,size_t _Size);
                  ^