src/mumble/OverlayText.h: add missing <QtGui/QPainterPath> include for Qt 5.15
../../release/.moc/mumble/../../../src/mumble/OverlayText.h:42:16: error: field ‘qpp’ has incomplete type ‘QPainterPath’
   42 |   QPainterPath qpp;
      |                ^~~