FIX(client, macos): Add conversion on TextToSpeech setVolume:volume
When attempting to compile mumble using LLVM on MacOS, the TextToSppech_macx.mm fails to compile due to an implicit conversion on settings the volume.

```
/Users/max/Projects/CLionProjects/mumble/src/mumble/TextToSpeech_macx.mm:138:48: error: implicit conversion from 'int' to 'float' may lose precision [-Werror,-Wimplicit-int-float-conversion]
138 | [[m_synthesizerHelper synthesizer] setVolume:volume / 100.0f];
    |                                              ^~~~~~ ~
```

This change adds the conversion from int to float.

(cherry picked from commit 0fcd8f968c112f2ef02897cfe91b5d44cf1e1ea6)