BUILD: Fix missing <cstdint> include
Without the change mumble build fails on this week's gcc-13 snapshot as:

    plugins/Module.h:13:9: error: 'uint64_t' does not name a type
       13 | typedef uint64_t procptr_t;
          |         ^~~~~~~~
    plugins/Module.h:12:1: note: 'uint64_t' is defined in header '<cstdint>';
      did you forget to '#include <cstdint>'?
       11 | #include <unordered_map>
      +++ |+#include <cstdint>
       12 |

Co-authored-by: Davide Beatrici <github@davidebeatrici.dev>
(cherry picked from commit b92d82d2b26426562a9c6b8a72ef5bd8035d5a10)