FIX(client): Capture "this" explicitly in lambdas
src/mumble/GlobalShortcut.cpp:96:74: error: implicit capture of 'this' with a capture default of '=' is deprecated [-Werror,-Wdeprecated-this-capture]
   96 |         connect(eventFilter, &KeyEventObserver::keyEventObserved, this, [=]() { m_comboBox->showPopup(); });
      |                                                                                 ^
src/mumble/GlobalShortcut.cpp:388:74: error: implicit capture of 'this' with a capture default of '=' is deprecated [-Werror,-Wdeprecated-this-capture]
  388 |         connect(eventFilter, &KeyEventObserver::keyEventObserved, this, [=]() { qtbEdit->click(); });
      |                                                                                 ^
src/mumble/GlobalShortcut.cpp:405:12: error: implicit capture of 'this' with a capture default of '=' is deprecated [-Werror,-Wdeprecated-this-capture]
  405 |                         [=]() { m_lineEdit->setFocus(Qt::MouseFocusReason); });
      |                                 ^

src/mumble/ListenerVolumeSlider.cpp:14:57: error: implicit capture of 'this' with a capture default of '=' is deprecated [-Werror,-Wdeprecated-this-capture]
   14 |         connect(&m_resetTimer, &QTimer::timeout, this, [=]() { m_currentSendDelay = 0; });
      |                                                                ^

src/mumble/VolumeSliderWidgetAction.cpp:49:3: error: implicit capture of 'this' with a capture default of '=' is deprecated [-Werror,-Wdeprecated-this-capture]
   49 |                 m_volumeSlider->setFocus(Qt::TabFocusReason);
      |                 ^
src/mumble/VolumeSliderWidgetAction.cpp:55:3: error: implicit capture of 'this' with a capture default of '=' is deprecated [-Werror,-Wdeprecated-this-capture]
   55 |                 m_volumeSlider->setFocus(Qt::TabFocusReason);
      |                 ^

(cherry picked from commit c34c96d66f7363c96e8ffa3b5ba4df08489920ce)