Global.cpp: Fix unused "migrateDataDir()" function on Windows
Also added comments near "#endif" to better understand the function
logic.

Fixes:
Global.cpp:12:13: error: 'void migrateDataDir()' defined but not used [-Werror=unused-function]
 static void migrateDataDir() {
             ^