FIX(client, server): Remove redundant OpenSSL locking callback check
CRYPTO_get_locking_callback() has been defined to NULL since OpenSSL
1.1.0.  This check therefore doesn't do anything in any supported
version of OpenSSL:

https://github.com/openssl/openssl/blob/abd30777cc72029e8a44e4b67201cae8ed3d19c1/include/openssl/crypto.h#L220

This fixes the following compiler error that I saw with GCC 14:

/build/source/src/SSL.cpp: In static member function ‘static void MumbleSSL::initialize()’:
/build/source/src/SSL.cpp:36:14: error: converting to ‘bool’ from ‘std::nullptr_t’ requires direct-initialization [-fpermissive]
   36 |         if (!CRYPTO_get_locking_callback()) {
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~

(cherry picked from commit 56945a9dfb62d29dccfe561572ebf64500deaed1)