murmur_pch.h: Include missing headers
Fixes:
error: 'socklen_t' does not name a type
error: invalid use of incomplete type 'sockaddr_in6'
error: 'IPV6_V6ONLY' was not declared in this scope
error: 'socklen_t' was not declared in this scope
error: 'optlen' was not declared in this scope
error: 'sockaddr_in6' does not name a type
error: 'QOS_NON_ADAPTIVE_FLOW' was not declared in this scope
error: 'QOSAddSocketToFlow' was not declared in this scope
error: 'QOSRemoveSocketFromFlow' was not declared in this scope
error: 'MSG_TRUNC' was not declared in this scope