WASAPI.h: Include missing header for MinGW on Linux
This fixes an error when compiling with MinGW on Linux.
error: 'PKEY_Device_FriendlyName' was not declared in this scope