src/Qt4Compat.h: add newline at end of file
The missing newline caused our Linux Ermine build to fail:

In file included from ../../src/Utils.h:14,
                 from murmur_pch.h:95:
../../src/Qt4Compat.h:17:7: error: no newline at end of file