mumble_plugin_utils.h: declare escape() as inline, minor improvements
Fixes the following warning:

../mumble_plugin_utils.h:33:13: error: 'void escape(char*, size_t)' defined but not used [-Werror=unused-function]
 static void escape(char *str, size_t size) {
             ^

It appeared after bb248cc, due to "ut99.cpp" not using escape().

This commit also:

- Changes the "size" argument so that it is passed as reference.
- Indents the function using tabs.