FIX(client): Use memset() to initialize VLA
src/mumble/PulseAudio.cpp:581:24: error: variable-sized object may not be initialized
                unsigned char buffer[bytes] = {};
                                     ^~~~~

(cherry picked from commit 4f593ed18cd386d02674abe23278d6520fbe2955)