BUILD(cmake): Find and link Poco::XML
Without this, building against the latest poco snapshot results in
errors like:

/usr/bin/ld: /builddir/build/BUILD/mumble-1.4.230.src/src/mumble/PluginManifest.cpp:72: undefined reference to `typeinfo for Poco::XML::Element'

(cherry picked from commit fefdd79ebcd53a3035967789d004938ee39e2030)

# Conflicts:
#	src/mumble/CMakeLists.txt