TaskList.cpp: fix compilation error with MinGW when PCH is disabled
Fixes the following error:

TaskList.cpp:77:20: error: 'SHARD_LINK' was not declared in this scope
  SHAddToRecentDocs(SHARD_LINK, link);
                    ^

"SHARD_LINK" is only defined when "NTDDI_VERSION" is at least "NTDDI_WIN7" (0x06010000).

We handle the logic for MinGW in "win.h", this commit fixes the error by including it.