Include "Global.h" after "Mumble.pb.h", to avoid a redefinition issue with protobuf 3.7
In protobuf 3.7 'g' is used as argument name, which conflicts with our global struct:

google/protobuf/stubs/strutil.h:720:47: error: 'g_global_struct' declared as a pointer to a reference of type 'const google::protobuf::strings::AlphaNum &'
                              const AlphaNum& g);
                                              ^
./Global.h:131:12: note: expanded from macro 'g'
           ^

The solution consists in including "Global.h" after any headers that include "Mumble.pb.h" (which in turn includes protobuf's headers).

"Mumble.pb.h" is generated by protobuf.