Fix Xi conflict that appears when MOC files are generated and included by CMake
Xi causes a conflict in the compiled MOC files when they are generated by CMake, because it defines a type called "Bool":

In file included from mumble/build/src/mumble/mumble_autogen/EWIEGA46WW/../../../../../src/mumble/GlobalShortcut_unix.h:14,
                 from mumble/build/src/mumble/mumble_autogen/EWIEGA46WW/moc_GlobalShortcut_unix.cpp:9,
                 from mumble/build/src/mumble/mumble_autogen/mocs_compilation.cpp:26:
mumble/build/src/mumble/mumble_autogen/EWIEGA46WW/moc_Log.cpp:191:89: error: expected unqualified-id before ‘int’
  191 |     QMetaType::Void, 0x80000000 | 3, QMetaType::QString, QMetaType::QString, QMetaType::Bool, QMetaType::QString,    4,    5,    6,    7,    8,
      |                                                                                         ^~~~
mumble/build/src/mumble/mumble_autogen/EWIEGA46WW/moc_Log.cpp:191:89: error: expected ‘}’ before ‘int’
In file included from mumble/build/src/mumble/mumble_autogen/mocs_compilation.cpp:29:
mumble/build/src/mumble/mumble_autogen/EWIEGA46WW/moc_Log.cpp:171:40: note: to match this ‘{’
  171 | static const uint qt_meta_data_Log[] = {
      |                                        ^
mumble/build/src/mumble/mumble_autogen/EWIEGA46WW/moc_Log.cpp:197:1: error: expected declaration before ‘}’ token
  197 | };
      | ^

The conflict appears in all "moc_*" files, but I truncated the output because it was very long (the message is repeated for each file).

I didn't investigate why it doesn't happen with qmake (it's probably due to the way MOC files are included), however including less headers in an header file is an improvement anyway.