Fix dangling else warning in ConnectDialog::OnSortChanged()
This commit fixes a warning encountered today on FreeBSD, probably because Clang was updated and now '-Wdangling-else' is enabled by default.

ConnectDialog.cpp:1178:3: error: add explicit braces to avoid dangling else [-Werror,-Wdangling-else]
                foreach(ServerItem *si, qlItems)
                ^