os_win.cpp: Fix unused "mumbleMessageOutput()" function
Fixes:
os_win.cpp:71:13: error: 'void mumbleMessageOutput(QtMsgType, const char*)' defined but not used [-Werror=unused-function]
 static void mumbleMessageOutput(QtMsgType type, const char *msg) {
             ^